!IF "$(CFG)" == "" 
CFG = Release
!ENDIF 

all:
   @cd vt++
   @nmake /nologo CFG=$(CFG) /F Makefile.w32

clean:
   @cd vt++
   @nmake /nologo CFG=$(CFG)  /F Makefile.w32 clean

check:
   @cd vt++
   @nmake /nologo CFG=$(CFG)  /F Makefile.w32 check


