#------------------------------------------------------------------------------
include ../config/ProjectDef.mk
include ../config/RootDef.mk
#------------------------------------------------------------------------------

ORAINC        = $(OCCIHOME)/sdk/include
#ORALIB       = $(OCCIHOME)

NAME          = EOracle

headers       = TOracleServerE2W.h TOracleServerE2.h TOracleServerE.h TOracleServer.h TOracleResult.h TOracleRow.h

PROJECT_LIBS  = $(PROJECT_LIBS)     -LIBPATH:$(OCCIHOME)/sdk/lib/msvc        \
                /DEFAULTLIB:ociw32  /DEFAULTLIB:oci  /DEFAULTLIB:oraocci10   \
                -lEdb -lEmath -lEphys -lvt -lEdr -lScan -lEMC 

INC_DIR       = $(INC_DIR)   -I$(ORAINC)
CXXFLAGS      = $(CXXFLAGS)  -DNOTROOTCINT

# rootcint needs -p option

#------------------------------------------------------------------------------
include ../config/TargetsDef.mk
#------------------------------------------------------------------------------
