/********************************************************************
* ACQCint.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error ACQCint.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableACQCint();
extern void G__cpp_setup_inheritanceACQCint();
extern void G__cpp_setup_typetableACQCint();
extern void G__cpp_setup_memvarACQCint();
extern void G__cpp_setup_globalACQCint();
extern void G__cpp_setup_memfuncACQCint();
extern void G__cpp_setup_funcACQCint();
extern void G__set_cpp_environmentACQCint();
}


#include "TROOT.h"
#include "TMemberInspector.h"
#include "AcqStage1.h"
#include "AcqOdyssey.h"
#include "AcqMarksScanner.h"
#include "AcqTrackScanner.h"
#include "AcqTrackReconstructor.h"
#include "AcqSerialPlateChanger.h"
#include "AcqCOM.h"

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__ACQCintLN_TClass;
extern G__linked_taginfo G__ACQCintLN_TBuffer;
extern G__linked_taginfo G__ACQCintLN_TMemberInspector;
extern G__linked_taginfo G__ACQCintLN_TObject;
extern G__linked_taginfo G__ACQCintLN_iteratorlErandom_access_iterator_tagcOcharcOlongcOcharmUcOcharaNgR;
extern G__linked_taginfo G__ACQCintLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR;
extern G__linked_taginfo G__ACQCintLN__RanitlETStreamerInfomUcOlongcOTStreamerInfomUmUcOTStreamerInfomUaNgR;
extern G__linked_taginfo G__ACQCintLN_iteratorlErandom_access_iterator_tagcOTStreamerInfomUcOlongcOTStreamerInfomUmUcOTStreamerInfomUaNgR;
extern G__linked_taginfo G__ACQCintLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ACQCintLN_iteratorlErandom_access_iterator_tagcOTStreamerInfomUcOvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorcLcLdifference_typecOTStreamerInfomUmUcOTStreamerInfomUaNgR;
extern G__linked_taginfo G__ACQCintLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLconst_iteratorgR;
extern G__linked_taginfo G__ACQCintLN_TClonesArray;
extern G__linked_taginfo G__ACQCintLN_TH1F;
extern G__linked_taginfo G__ACQCintLN_EdbAffine2D;
extern G__linked_taginfo G__ACQCintLN_EdbMarksSet;
extern G__linked_taginfo G__ACQCintLN_EdbArea;
extern G__linked_taginfo G__ACQCintLN_AcqAxis;
extern G__linked_taginfo G__ACQCintLN_AcqLight;
extern G__linked_taginfo G__ACQCintLN_AcqStage1;
extern G__linked_taginfo G__ACQCintLN_EdbClustersBox;
extern G__linked_taginfo G__ACQCintLN_EdbFrame;
extern G__linked_taginfo G__ACQCintLN_EdbView;
extern G__linked_taginfo G__ACQCintLN_EdbImage;
extern G__linked_taginfo G__ACQCintLN_AcqOdyssey;
extern G__linked_taginfo G__ACQCintLN_AcqMarksScanner;
extern G__linked_taginfo G__ACQCintLN_EdbRun;
extern G__linked_taginfo G__ACQCintLN_AcqTrackScanner;
extern G__linked_taginfo G__ACQCintLN_AcqTrackReconstructor;
extern G__linked_taginfo G__ACQCintLN_AcqCOM;
extern G__linked_taginfo G__ACQCintLN_IdentifierS;
extern G__linked_taginfo G__ACQCintLN_TPlateS;
extern G__linked_taginfo G__ACQCintLN_AcqSerialPlateChanger;

/* STUB derived class for protected member access */
