#------------------------------------------------------------------------------
include ../config/ProjectDef.mk
include ../config/RootDef.mk
#------------------------------------------------------------------------------

NAME          = Alignment

headers       =  EdbPatCell2.h EdbPositionAlignment.h EdbAlignmentMap.h EdbPeakProb.h EdbTestAl.h 

PROJECT_LIBS  = $(PROJECT_LIBS) -lEmath -lEdb -lvt -lEdr -lEIO -lEMC -lDataConversion

#------------------------------------------------------------------------------
include ../config/TargetsDef.mk
#------------------------------------------------------------------------------
