#------------------------------------------------------------------------------
include ../config/ProjectDef.mk
include ../config/RootDef.mk
#------------------------------------------------------------------------------

NAME          = EIO

headers       = EdbDataSet.h EdbTraceBack.h EdbRunAccess.h

PROJECT_LIBS  = $(PROJECT_LIBS) -lEdb -lEdr -lEmath -lDataConversion

#------------------------------------------------------------------------------
include ../config/TargetsDef.mk
#------------------------------------------------------------------------------
