#------------------------------------------------------------------------------
include ../config/ProjectDef.mk
include ../config/RootDef.mk
#------------------------------------------------------------------------------

NAME          = EIO

headers       = EdbRunAccess.h EdbDataSet.h EdbTraceBack.h

PROJECT_LIBS  = $(PROJECT_LIBS) -lEdb -lEdr -lEmath

#------------------------------------------------------------------------------
include ../config/TargetsDef.mk
#------------------------------------------------------------------------------
