#------------------------------------------------------------------------------
include ../../config/ProjectDef.mk
include ../../config/RootDef.mk
#------------------------------------------------------------------------------

NAME = recset

PROJECT_LIBS = $(PROJECT_LIBS) -lEdb -lEdr -lEdr -lEmath -lEphys -lvt -lEIO

#------------------------------------------------------------------------------
include ../../config/TargetsDefAppl.mk
