#------------------------------------------------------------------------------
include ../../config/ProjectDef.mk
include ../../config/RootDef.mk
#------------------------------------------------------------------------------

TARGET  =       $(BIN_DIR)/recset$(ExeSuf)

PROJECT_LIBS = -lEdb -lEdr -lEdr -lEmath -lEphys -lvt -lEIO -lDataConversion

#------------------------------------------------------------------------------
include ../../config/TargetsDef.mk
#--------------------------------------------------------------------------
