#------------------------------------------------------------------------------
include ../../config/ProjectDef.mk
include ../../config/RootDef.mk
#------------------------------------------------------------------------------

PROJECT_LIBS = $(PROJECT_LIBS)  libEdb.lib  libEdd.lib libEdr.lib libEdr.lib \
                       libEmath.lib libEphys.lib libvt.lib libEIO.lib

CPPFLAGS     = $(CPPFLAGS) -I$(INC_DIR)

recset.exe : recset.obj
	$(LD) $**  $(LIBS) $(PROJECT_LIBS) -out:$(BIN_DIR)/$@

#------------------------------------------------------------------------------
clean:
    @del /q recset.obj "$(BIN_DIR)"\recset.exe