#------------------------------------------------------------------------------
include ../config/ProjectDef.mk
include ../config/RootDef.mk
#------------------------------------------------------------------------------

NAME          = Emath

headers       = TIndexCell.h EdbMath.h EdbCell2.h EdbCell1.h EdbMask.h EdbCombGen.h

PROJECT_LIBS  = $(PROJECT_LIBS) -lEdb

#------------------------------------------------------------------------------
include ../config/TargetsDef.mk
#------------------------------------------------------------------------------
