#------------------------------------------------------------------------------
include ../../config/ProjectDef.mk
include ../../config/RootDef.mk
#------------------------------------------------------------------------------

PROJECT_LIBS = $(PROJECT_LIBS)  libEdb.lib  libEdd.lib libEdr.lib libEdr.lib \
                       libEmath.lib libEphys.lib libvt++.lib libEIO.lib

CPPFLAGS     = $(CPPFLAGS) -I$(INC_DIR)

cp2edb.exe: cp2edb.obj
      $(LD) $**  $(LIBS) $(PROJECT_LIBS) -out:$(BIN_DIR)/$@

#------------------------------------------------------------------------------
clean:
    @del /q cp2edb.obj "$(BIN_DIR)"\cp2edb.exe
