#------------------------------------------------------------------------------
include ../../config/ProjectDef.mk
include ../../config/RootDef.mk
#------------------------------------------------------------------------------

TARGET  =       $(BIN_DIR)/m2track$(ExeSuf)

PROJECT_LIBS = -lEdb -lEdr -lEdr -lEmath -lEphys -lEbase -lvt -lEIO -lDataConversion -lAlignment -lEdb -lEdr -lEdr -lEmath -lEphys -lEbase -lvt -lEIO -lDataConversion -lAlignment $(ROOTLIBS)

#------------------------------------------------------------------------------
include ../../config/TargetsDef.mk
#--------------------------------------------------------------------------
