#include <stdlib.h>
#include <iostream>
#include <fstream>

#include "Riostream.h"
#include <TROOT.h>
#include <TObject.h>
#include <TApplication.h>
#include <TVirtualX.h>
#include <TGResourcePool.h>
#include <TGListBox.h>
#include <TGListTree.h>
#include <TGFSContainer.h>
#include <TGClient.h>
#include <TGFrame.h>
#include <TGIcon.h>
#include <TGLabel.h>
#include <TGButton.h>
#include <TGTextEntry.h>
#include <TGNumberEntry.h>
#include <TGMsgBox.h>
#include <TGMenu.h>
#include <TGCanvas.h>
#include <TGComboBox.h>
#include <TGTab.h>
#include <TGSlider.h>
#include <TGDoubleSlider.h>
#include <TGFileDialog.h>
#include <TGTextEdit.h>
#include <TGShutter.h>
#include <TGProgressBar.h>
#include <TGStatusBar.h>
#include <TGColorSelect.h>
#include <RQ_OBJECT.h>
#include <TRootEmbeddedCanvas.h>
#include <TCanvas.h>
#include <TH1.h>
#include <TH2.h>
#include <TH3.h>
#include <TSpectrum2.h>
#include <TRandom.h>
#include <TSystem.h>
#include <TSystemDirectory.h>
#include <TEnv.h>
#include <TFile.h>
#include <TKey.h>
#include <TRootHelpDialog.h>
#include <TPolyLine.h>
#include <TPolyLine3D.h>
#include <TPolyMarker.h>
#include <TPolyMarker3D.h>
#include <TTree.h>
#include <TView.h>
#include <TViewerX3D.h>
#include <TProfile.h>
#include "TStyle.h"
#include "TMinuit.h"
#include "TVirtualFitter.h"
#include "TLegend.h"
#include "TMath.h"
#include <TMultiLayerPerceptron.h>
#include <TMLPAnalyzer.h>
#include <TProfile.h>
#include <TTreeFormula.h>
#include "TTreePlayer.h"

#include "EdbDataSet.h"
#include "EdbPattern.h"
#include "EdbPVRec.h"
#include "EdbLog.h"
#include "EdbVertex.h"
#include "EdbDataSet.h"
#include "EdbMath.h"
#include "EdbSegP.h"
#include "EdbPVRQuality.h"

#include "vt++/VtTrack.hh"
#include "vt++/VtVertex.hh"
#include "vt++/CMatrix.hh"