#------------------------------------------------------------------------------
include $(FEDRA_ROOT)/src/config/ProjectDef.mk
include $(FEDRA_ROOT)/src/config/RootDef.mk
#------------------------------------------------------------------------------

TARGET	=	$(BIN_DIR)/rwc2edb$(ExeSuf)      \
     		$(BIN_DIR)/rwdread$(ExeSuf)      \
		$(BIN_DIR)/rwcread$(ExeSuf)      \
		$(BIN_DIR)/rwdcomp$(ExeSuf)      

#		$(BIN_DIR)/getacqstatus$(ExeSuf)
#		$(BIN_DIR)/edb2rwc$(ExeSuf)    

PROJECT_LIBS  = -lEdb -lDataConversion

#------------------------------------------------------------------------------
include ../../config/TargetsDef.mk
#--------------------------------------------------------------------------
