#------------------------------------------------------------------------------
include ../config/ProjectDef.mk
include ../config/RootDef.mk
#------------------------------------------------------------------------------

NAME          = Analysis

headers       = EdbDecaySearch.h

PROJECT_LIBS  = $(PROJECT_LIBS)  -lEmath -lEdb -lEbase -lEdr -lEphys -lEIO -lEve -lGui -lRGL -lScan -lShower -lVt -lEDA

#------------------------------------------------------------------------------
include ../config/TargetsDef.mk
#------------------------------------------------------------------------------
