#------------------------------------------------------------------------------
include ../../config/ProjectDef.mk
include ../../config/RootDef.mk
#------------------------------------------------------------------------------

PROJECT_LIBS = $(PROJECT_LIBS)  libEdb.lib  libEdd.lib libEdr.lib libEdr.lib \
                       libEmath.lib libEphys.lib libvt.lib libEIO.lib

CPPFLAGS     = $(CPPFLAGS) -I$(INC_DIR)

checkrun.exe : checkrun.obj
	$(LD) $**  $(LIBS) $(PROJECT_LIBS) -out:$(BIN_DIR)/$@

#------------------------------------------------------------------------------
clean:
    @del /q checkrun.obj "$(BIN_DIR)"\checkrun.exe