#------------------------------------------------------------------------------
include ../config/ProjectDef.mk
include ../config/RootDef.mk
#------------------------------------------------------------------------------

NAME          = Edr

headers       = EdbPattern.h EdbPVRec.h EdbVertex.h EdbVertexComb.h EdbVertexSpace.h EdbTrackFitter.h EdbMomentumEstimator.h EdbPlateTracking.h

PROJECT_LIBS  = $(PROJECT_LIBS) -lvt -lEmath -lEdb -lEbase -lEphys -lAlignment

#------------------------------------------------------------------------------
include ../config/TargetsDef.mk
#------------------------------------------------------------------------------
