#------------------------------------------------------------------------------
include ../../config/ProjectDef.mk
include ../../config/RootDef.mk
#------------------------------------------------------------------------------

NAME         = tracks2edb

PROJECT_LIBS = $(PROJECT_LIBS) -lEdb -lEIO -lEmath

#------------------------------------------------------------------------------
include ../../config/TargetsDefAppl.mk
