#------------------------------------------------------------------------------
include ../config/ProjectDef.mk
include ../config/RootDef.mk
#------------------------------------------------------------------------------

NAME          = EDA

headers       = EdbEDA.h EdbEDAUtil.h EdbEDATrackSet.h EdbEDASets.h EdbEDAMainTab.h EdbEDATabs.h EdbEDAPlotTab.h EdbEDADecaySearch.h EdbEDAShowerTab.h

PROJECT_LIBS  = $(PROJECT_LIBS)  -lEmath -lEdb -lEbase -lEdr -lEphys -lEIO -lEve -lGui -lRGL -lScan -lShower

#------------------------------------------------------------------------------
include ../config/TargetsDef.mk
#------------------------------------------------------------------------------
