#------------------------------------------------------------------------------
include ../../config/ProjectDef.mk
include ../../config/RootDef.mk
#------------------------------------------------------------------------------

TARGET	=	$(BIN_DIR)/comptonmap$(ExeSuf)

PROJECT_LIBS = -lEdb -lEbase -lEdr -lEbase -lEmath -lEphys -lvt -lEIO -lDataConversion -lAlignment -lScan -lEMC

#------------------------------------------------------------------------------
include ../../config/TargetsDef.mk
#--------------------------------------------------------------------------
