#------------------------------------------------------------------------------
include ../../config/ProjectDef.mk
include ../../config/RootDef.mk
#------------------------------------------------------------------------------

TARGET	=	$(BIN_DIR)/comptonmap$(ExeSuf)

PROJECT_LIBS = -lEdb -lEdr -lEmath -lEphys -lvt -lEIO -lDataConversion -lAlignment -lScan -lEMC

##PROJECT_LIBS += -L$(FEDRA_ROOT)/lib -lScan -lEdb -lEmath -lEphys -lvt -lEdr -lScan -lEdr -lEIO -lEMC -lDataConversion

#------------------------------------------------------------------------------
include ../../config/TargetsDef.mk
#--------------------------------------------------------------------------
