#------------------------------------------------------------------------------
include ../config/ProjectDef.mk
include ../config/RootDef.mk
#------------------------------------------------------------------------------

NAME          = Edb

headers       = EdbCluster.h EdbView.h EdbRunHeader.h EdbRun.h \
		EdbImage.h EdbFrame.h EdbSegment.h EdbStage.h \
		EdbAffine.h EdbFiducial.h EdbVirtual.h EdbPrediction.h \
		EdbOnline.h

#------------------------------------------------------------------------------
include ../config/TargetsDef.mk
#------------------------------------------------------------------------------
