#------------------------------------------------------------------------------
include ../config/ProjectDef.mk
include ../config/RootDef.mk
#------------------------------------------------------------------------------

NAME          = Edd

headers       = EdbDisplayBase.h  EdbDisplay.h

PROJECT_LIBS  = $(PROJECT_LIBS) $(GLIBS) -lEmath -lEdb -lvt -lEdr -lEbase

#------------------------------------------------------------------------------
include ../config/TargetsDef.mk
#------------------------------------------------------------------------------
