#------------------------------------------------------------------------------
include ../../config/ProjectDef.mk
include ../../config/RootDef.mk
#------------------------------------------------------------------------------

TARGET  =   $(BIN_DIR)/addRWC$(ExeSuf)       \
			$(BIN_DIR)/addRWD$(ExeSuf)       \
			$(BIN_DIR)/check_raw$(ExeSuf)    \
			$(BIN_DIR)/check_cp$(ExeSuf)     \
			$(BIN_DIR)/check_tr$(ExeSuf)     \
			$(BIN_DIR)/edbtools$(ExeSuf)     \
			$(BIN_DIR)/tracks2edb$(ExeSuf)   \
			$(BIN_DIR)/tlg2couples$(ExeSuf)  \
			$(BIN_DIR)/checkrun$(ExeSuf)     
    
PROJECT_LIBS  = -lEdb -lEbase -lDataConversion -lEIO -lEdr -lEmath -lvt -lEphys -lAlignment -lEdb -lEbase -lDataConversion -lEIO -lEdr -lEmath -lvt -lEphys -lAlignment -lEIO $(ROOTLIBS)

#------------------------------------------------------------------------------
include ../../config/TargetsDef.mk
#------------------------------------------------------------------------------
