#------------------------------------------------------------------------------
include ../../config/ProjectDef.mk
include ../../config/RootDef.mk
#------------------------------------------------------------------------------

TARGET        = $(BIN_DIR)/display$(ExeSuf)
EXTRALIBS     = -lThread -lGui
PROJECT_LIBS  = $(EXTRALIBS) -lEdr -lEdb -lEIO -lEmath -lEphys -lvt \
		-lDataConversion -lEGraphTool -lScan -lEMC

#------------------------------------------------------------------------------
include ../../config/TargetsDef.mk
#------------------------------------------------------------------------------
