#------------------------------------------------------------------------------
include ../config/ProjectDef.mk
include ../config/RootDef.mk
#------------------------------------------------------------------------------

NAME          = EGraphTool

headers       = EGraphTool.h EGraphRec.h EGraphHits.h

PROJECT_LIBS  = $(GLIBS) -lEdb -lScan

#------------------------------------------------------------------------------
include ../config/TargetsDef.mk
#------------------------------------------------------------------------------
