#------------------------------------------------------------------------------
include ../config/ProjectDef.mk
include ../config/RootDef.mk
#------------------------------------------------------------------------------

NAME          = EGraphTool

headers       = EGraphTool.h EGraphRec.h EGraphRecProc.h EGraphHits.h

EXTRALIBS     = -lThread -lGui

PROJECT_LIBS  = $(EXTRALIBS) -lEdb -lScan -lEdr

#------------------------------------------------------------------------------
include ../config/TargetsDef.mk
#------------------------------------------------------------------------------
