#------------------------------------------------------------------------------
include ../config/ProjectDef.mk
include ../config/RootDef.mk
#------------------------------------------------------------------------------

NAME          = EGraphTool

headers       = EGraphTool.h EGraphRec.h EGraphHits.h

#PROJECT_LIBS  = $(PROJECT_LIBS) -lvt -lEmath -lEdb -lEphys

#------------------------------------------------------------------------------
include ../config/TargetsDef.mk
#------------------------------------------------------------------------------
