#------------------------------------------------------------------------------
include ../config/ProjectDef.mk
include ../config/RootDef.mk
#------------------------------------------------------------------------------

NAME          = EMC

headers       = EdbPVGen.h EdbBrickGen.h EdbBrick.h EdbViewDef.h EdbViewGen.h EdbViewRec.h

PROJECT_LIBS  = $(PROJECT_LIBS) -lEdr -lEdb -lEphys -lEmath

#------------------------------------------------------------------------------
include ../config/TargetsDef.mk
#------------------------------------------------------------------------------
