#------------------------------------------------------------------------------
include ../config/ProjectDef.mk
include ../config/RootDef.mk
#------------------------------------------------------------------------------

NAME          = EMC

headers       = EdbPVGen.h EdbBrickGen.h EdbBrick.h EdbViewGen.h

PROJECT_LIBS  = $(PROJECT_LIBS) -lEdr -lEdb -lEphys

#------------------------------------------------------------------------------
include ../config/TargetsDef.mk
#------------------------------------------------------------------------------
