#------------------------------------------------------------------------------
include ../config/ProjectDef.mk
include ../config/RootDef.mk
#------------------------------------------------------------------------------

NAME          = Ebase

headers       = EdbSegCorr.h EdbLayer.h EdbScanCond.h EdbBrick.h EdbScanSet.h EdbID.h EdbSegP.h EdbSigma.h EdbSEQ.h EdbCouplesTree.h EdbSegCouple.h EdbSegmentCut.h

PROJECT_LIBS  = $(PROJECT_LIBS) -lEdb -lEmath -lvt -lEdr

#------------------------------------------------------------------------------
include ../config/TargetsDef.mk
#------------------------------------------------------------------------------
