#------------------------------------------------------------------------------
include ../../config/ProjectDef.mk
include ../../config/RootDef.mk
#------------------------------------------------------------------------------

NAME          = bmatrix

headers       = bitmatrix.h basematrix.h bytematrix.h bitview.h

PROJECT_LIBS = $(PROJECT_LIBS) -lEdb 

#------------------------------------------------------------------------------
include ../../config/TargetsDef.mk
#------------------------------------------------------------------------------
